version: '3.1'

services:
  nginx:
    restart: always
    container_name:  web_report_nginx
    image: nginx:1.23.3
    expose:
      - 8081
    ports:
      - "81:8081"
    volumes:
      - "./static:/srv/www/web-report/static"
      - "./sitename.conf:/etc/nginx/conf.d/sitename.conf"
    depends_on:
      - web_python

  web_python:
    restart: always
    container_name:  web_report_python39

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ".:/srv/www/web-report"

    command: "gunicorn -b 0.0.0.0:8000 web_report.wsgi:application"

    env_file:
      - .env

  redis:
    image: redis:6.2.10
    container_name:  web_report_redis

  celery:
    container_name:  web_report_celery
    restart: always

    build:
      context: .
    command: celery -A web_report worker --loglevel=info --logfile=celery-worker.log

    volumes:
      - ".:/srv/www/web-report"
    env_file:
      - .env
    depends_on:
      - redis
