version: '3.8'

services:
  nginx:
    restart: always
    image: nginx:1.23.3
    expose:
      - 8080
    ports:
      - "80:8080"
    volumes:
      - "./static:/srv/www/web-report/static"
      - "./media:/srv/www/web-report/media"
      #      - "./logs:/srv/www/web-report/logs"
      - "./sitename.conf:/etc/nginx/conf.d/sitename.conf"
    depends_on:
      - web_python

  web_python:
    restart: always

    build:
#      context: .
      dockerfile: Dockerfile

    volumes:
      - ".:/srv/www/web-report"

    command: "gunicorn -b 0.0.0.0:8000 web_report.wsgi:application"

    env_file:
      - ./.env.dev

  redis:
    image: redis:6.2.10

  celery:
    build:
#      context: .
      dockerfile: Dockerfile
    command: celery -A web_report worker -l info
    volumes:
      - ".:/srv/www/web-report"
    depends_on:
      - redis
